name: oprod.net
description: Blogging about my projects, Ruby on Rails and RubyMotion
meta_description: "oprod.net, Blogging about my projects, Ruby on Rails and RubyMotion"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://oprod.net'
google_analytics: 'UA-2141963-1'

# Details for the RSS feed generator
url:            'http://oprod.net'
author:         'Andrei G'
bio: 😱

permalink: /:title/

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
